// <auto-generated />
namespace NHibernateMigrate.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogAndPostHasNoPrimaryKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogAndPostHasNoPrimaryKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "201209251346151_BlogAndPostHasNoPrimaryKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
